#!/usr/bin/env bash
# Install and configure HAproxy

# Update Packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add Haproxy PPA
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.5
app-get -y update

# Install Haproxy
apt-get -y install haproxy=2.5.\*
# edit config file
server_config=\
"
frontend  karmadi_frontend
        bind *:80
        mode http
        default_backend karmadi_backend
backend karmadi_backend
        balance roundrobin
        server 365502-web-01 18.206.208.13:80 check
        server 365502-web-02 100.25.194.30:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
